- name: Loops in Ansible
  hosts: localhost
  connection: local
  vars:
    fruits:
      - apple
      - banana
      - orange
    sweets:
      sweet: 
        name: badusha
        stock_available: true
        price: 100K
      sweet:
        name: jilebi
        stock_available: false
        price: 200K
        from: AP
  tasks:
    - name: Accesing the list variables
      ansible.builtin.debug:
        msg: "fruits name = {{ item }}"
      loop: "{{fruits}}"
    - name: Accessing the dict variables
      ansible.builtin.debug:
        msg: "Seet Names Are {{ item.sweet.name }}"
      loop: "{{sweets}}"
